In [4]:
# %load a_star.py
# Finish A* search function that can find path from starting point to the end
# The robot starts from start position (0,0) and finds a path to end position (4, 5)
# In the maze, 0 is open path while 1 means wall (a robot cannot pass through wall)
# please write your heuristic matrix, and fill unvisited position with -1,
# cost of each movement is 1, as shown in the example below

# example result:
# [[0, -1, -1, -1, -1, -1],
#  [1, -1, -1, -1, -1, -1],
#  [2, -1, -1, -1, -1, -1],
#  [3, -1,  8, 10, 12, 14],
#  [4,  5,  6,  7, -1, 15]]

# the maze robot need to find a path
maze = [[0, 1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 1, 0]]

start = [0, 0] # starting position
end = [len(maze)-1, len(maze[0])-1] # ending position
cost = 1 # cost per movement

move = [[-1, 0 ], # go up
        [ 0, -1], # go left
        [ 1, 0 ], # go down
        [ 0, 1 ]] # go right


### 1. make your own heuristic
heuristic = [[0, 0, 0, 0, 0, 0],
             [0, 0, 0, 0, 0, 0],
             [0, 0, 0, 0, 0, 0],
             [0, 0, 0, 0, 0, 0],
             [0, 0, 0, 0, 0, 0]]


### 2. finish the A* search funciton below
# def search(maze, start, end, cost, heuristic):
    
#     # first convert everything to numpy array for each slicking/referece
#     import numpy as np
    
#     maze = np.array(maze)
#     start = np.array(start)
#     end = np.array(end)
#     move = np.array([[-1, 0 ], # go up
#         [ 0, -1], # go left
#         [ 1, 0 ], # go down
#         [ 0, 1 ]] # go right
#     )
#     # initialize starting location and total cost
#     ind = start
#     cumulative_cost = 0
    
#     while (ind[0]!= end[0] | ind[1]!= end[1]):
#         # get direction
#         direction = end - start
#         direction = np.array([1 if i > 0 else 0 for i in direction ])
#         # get next move from move matrix
        
#         # left_right
#         left_right = move[[1,3]][direction[0]]
#         # up_down
#         left_right = move[[0,2]][direction[1]]
        
#         # check if already travelled
#         for next_move in [left_right, up_down, -left_right, -up_down]: 
#             check = ind + next_move
#             if maze[check]!= 1: # not wall
#                 # make the move
#                 ind = check
#                 maze[ind] = cumulative_cost +1
#                 cumulative_cost = maze[ind]
#                 print(maze)

#     return 

# search(maze, start, end, cost, heuristic)

In [5]:
# initialize starting location and total cost
import numpy as np
ind = start
cumulative_cost = 0
print(np.array(maze))

[[0 1 0 0 0 0]
 [0 1 0 0 0 0]
 [0 1 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 0 0 1 0]]


In [6]:
while (~(ind[0]!= end[0] & ind[1]!= end[1])):
    
    # get preferred direction from the current location to destination
    direction = [end[0] - ind[0] , end[1] - ind[1]]
    direction = [1 if i > 0 else 0 for i in direction ]
    print('direction: {}'.format(direction))
    
    # get potential next move from move matrix
    first_left_right = move[1:4:2][direction[0]] # left_right
    first_up_down = move[0:3:2][direction[1]] # up_down   
    second_left_right = move[1:4:2][1- direction[0]]
    second_up_down = move[0:3:2][1- direction[1]]
    
    print('first left_right: {}'.format(first_left_right))
    print('first up_down: {}'.format(first_up_down))

    for next_move in [first_left_right, first_up_down, second_left_right, second_up_down]:
        
        check = [ind[0] + next_move[0] ,ind[1] + next_move[1]]  
        print('check: {}'.format(check))     
        
        if ((check[0]>=0) & (check[0] < len(maze)) & (check[1] >= 0) & (check[1] < len(maze[0]))): 
            # check if the next move was already travelled, or at the bundary
            if (maze[check[0]][check[1]] != 1): # not wall, let's make the move
                ind = check
                cumulative_cost = cumulative_cost +1
                maze[ind[0]][ind[1]] = cumulative_cost
                print(np.array(maze))
                break # after making the move, return to the iteration
        else:
            continue
        

direction: [1, 1]
first left_right: [0, 1]
first up_down: [1, 0]
check: [0, 1]
check: [1, 0]
[[0 1 0 0 0 0]
 [1 1 0 0 0 0]
 [0 1 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 0 0 1 0]]
direction: [1, 1]
first left_right: [0, 1]
first up_down: [1, 0]
check: [1, 1]
check: [2, 0]
[[0 1 0 0 0 0]
 [1 1 0 0 0 0]
 [2 1 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 0 0 1 0]]
direction: [1, 1]
first left_right: [0, 1]
first up_down: [1, 0]
check: [2, 1]
check: [3, 0]
[[0 1 0 0 0 0]
 [1 1 0 0 0 0]
 [2 1 0 0 0 0]
 [3 1 0 0 0 0]
 [0 0 0 0 1 0]]
direction: [1, 1]
first left_right: [0, 1]
first up_down: [1, 0]
check: [3, 1]
check: [4, 0]
[[0 1 0 0 0 0]
 [1 1 0 0 0 0]
 [2 1 0 0 0 0]
 [3 1 0 0 0 0]
 [4 0 0 0 1 0]]
direction: [0, 1]
first left_right: [0, -1]
first up_down: [1, 0]
check: [4, -1]
check: [5, 0]
check: [4, 1]
[[0 1 0 0 0 0]
 [1 1 0 0 0 0]
 [2 1 0 0 0 0]
 [3 1 0 0 0 0]
 [4 5 0 0 1 0]]
direction: [0, 1]
first left_right: [0, -1]
first up_down: [1, 0]
check: [4, 0]
[[0 1 0 0 0 0]
 [1 1 0 0 0 0]
 [2 1 0 0 0 0]
 [3 1 0 0 0 0]

check: [4, 1]
[[  0   1   0   0   0   0]
 [  1   1   0   0   0   0]
 [  2   1   0   0   0   0]
 [  3   1   0   0   0   0]
 [260 261   0   0   1   0]]
direction: [0, 1]
first left_right: [0, -1]
first up_down: [1, 0]
check: [4, 0]
[[  0   1   0   0   0   0]
 [  1   1   0   0   0   0]
 [  2   1   0   0   0   0]
 [  3   1   0   0   0   0]
 [262 261   0   0   1   0]]
direction: [0, 1]
first left_right: [0, -1]
first up_down: [1, 0]
check: [4, -1]
check: [5, 0]
check: [4, 1]
[[  0   1   0   0   0   0]
 [  1   1   0   0   0   0]
 [  2   1   0   0   0   0]
 [  3   1   0   0   0   0]
 [262 263   0   0   1   0]]
direction: [0, 1]
first left_right: [0, -1]
first up_down: [1, 0]
check: [4, 0]
[[  0   1   0   0   0   0]
 [  1   1   0   0   0   0]
 [  2   1   0   0   0   0]
 [  3   1   0   0   0   0]
 [264 263   0   0   1   0]]
direction: [0, 1]
first left_right: [0, -1]
first up_down: [1, 0]
check: [4, -1]
check: [5, 0]
check: [4, 1]
[[  0   1   0   0   0   0]
 [  1   1   0   0   0   0]
 [  2   1 

check: [5, 0]
check: [4, 1]
[[  0   1   0   0   0   0]
 [  1   1   0   0   0   0]
 [  2   1   0   0   0   0]
 [  3   1   0   0   0   0]
 [510 511   0   0   1   0]]
direction: [0, 1]
first left_right: [0, -1]
first up_down: [1, 0]
check: [4, 0]
[[  0   1   0   0   0   0]
 [  1   1   0   0   0   0]
 [  2   1   0   0   0   0]
 [  3   1   0   0   0   0]
 [512 511   0   0   1   0]]
direction: [0, 1]
first left_right: [0, -1]
first up_down: [1, 0]
check: [4, -1]
check: [5, 0]
check: [4, 1]
[[  0   1   0   0   0   0]
 [  1   1   0   0   0   0]
 [  2   1   0   0   0   0]
 [  3   1   0   0   0   0]
 [512 513   0   0   1   0]]
direction: [0, 1]
first left_right: [0, -1]
first up_down: [1, 0]
check: [4, 0]
[[  0   1   0   0   0   0]
 [  1   1   0   0   0   0]
 [  2   1   0   0   0   0]
 [  3   1   0   0   0   0]
 [514 513   0   0   1   0]]
direction: [0, 1]
first left_right: [0, -1]
first up_down: [1, 0]
check: [4, -1]
check: [5, 0]
check: [4, 1]
[[  0   1   0   0   0   0]
 [  1   1   0   0   0  

check: [5, 0]
check: [4, 1]
[[  0   1   0   0   0   0]
 [  1   1   0   0   0   0]
 [  2   1   0   0   0   0]
 [  3   1   0   0   0   0]
 [760 761   0   0   1   0]]
direction: [0, 1]
first left_right: [0, -1]
first up_down: [1, 0]
check: [4, 0]
[[  0   1   0   0   0   0]
 [  1   1   0   0   0   0]
 [  2   1   0   0   0   0]
 [  3   1   0   0   0   0]
 [762 761   0   0   1   0]]
direction: [0, 1]
first left_right: [0, -1]
first up_down: [1, 0]
check: [4, -1]
check: [5, 0]
check: [4, 1]
[[  0   1   0   0   0   0]
 [  1   1   0   0   0   0]
 [  2   1   0   0   0   0]
 [  3   1   0   0   0   0]
 [762 763   0   0   1   0]]
direction: [0, 1]
first left_right: [0, -1]
first up_down: [1, 0]
check: [4, 0]
[[  0   1   0   0   0   0]
 [  1   1   0   0   0   0]
 [  2   1   0   0   0   0]
 [  3   1   0   0   0   0]
 [764 763   0   0   1   0]]
direction: [0, 1]
first left_right: [0, -1]
first up_down: [1, 0]
check: [4, -1]
check: [5, 0]
check: [4, 1]
[[  0   1   0   0   0   0]
 [  1   1   0   0   0  

check: [4, -1]
check: [5, 0]
check: [4, 1]
[[   0    1    0    0    0    0]
 [   1    1    0    0    0    0]
 [   2    1    0    0    0    0]
 [   3    1    0    0    0    0]
 [1010 1011    0    0    1    0]]
direction: [0, 1]
first left_right: [0, -1]
first up_down: [1, 0]
check: [4, 0]
[[   0    1    0    0    0    0]
 [   1    1    0    0    0    0]
 [   2    1    0    0    0    0]
 [   3    1    0    0    0    0]
 [1012 1011    0    0    1    0]]
direction: [0, 1]
first left_right: [0, -1]
first up_down: [1, 0]
check: [4, -1]
check: [5, 0]
check: [4, 1]
[[   0    1    0    0    0    0]
 [   1    1    0    0    0    0]
 [   2    1    0    0    0    0]
 [   3    1    0    0    0    0]
 [1012 1013    0    0    1    0]]
direction: [0, 1]
first left_right: [0, -1]
first up_down: [1, 0]
check: [4, 0]
[[   0    1    0    0    0    0]
 [   1    1    0    0    0    0]
 [   2    1    0    0    0    0]
 [   3    1    0    0    0    0]
 [1014 1013    0    0    1    0]]
direction: [0, 1]
first 

check: [4, -1]
check: [5, 0]
check: [4, 1]
[[   0    1    0    0    0    0]
 [   1    1    0    0    0    0]
 [   2    1    0    0    0    0]
 [   3    1    0    0    0    0]
 [1260 1261    0    0    1    0]]
direction: [0, 1]
first left_right: [0, -1]
first up_down: [1, 0]
check: [4, 0]
[[   0    1    0    0    0    0]
 [   1    1    0    0    0    0]
 [   2    1    0    0    0    0]
 [   3    1    0    0    0    0]
 [1262 1261    0    0    1    0]]
direction: [0, 1]
first left_right: [0, -1]
first up_down: [1, 0]
check: [4, -1]
check: [5, 0]
check: [4, 1]
[[   0    1    0    0    0    0]
 [   1    1    0    0    0    0]
 [   2    1    0    0    0    0]
 [   3    1    0    0    0    0]
 [1262 1263    0    0    1    0]]
direction: [0, 1]
first left_right: [0, -1]
first up_down: [1, 0]
check: [4, 0]
[[   0    1    0    0    0    0]
 [   1    1    0    0    0    0]
 [   2    1    0    0    0    0]
 [   3    1    0    0    0    0]
 [1264 1263    0    0    1    0]]
direction: [0, 1]
first 

first up_down: [1, 0]
check: [4, -1]
check: [5, 0]
check: [4, 1]
[[   0    1    0    0    0    0]
 [   1    1    0    0    0    0]
 [   2    1    0    0    0    0]
 [   3    1    0    0    0    0]
 [1510 1511    0    0    1    0]]
direction: [0, 1]
first left_right: [0, -1]
first up_down: [1, 0]
check: [4, 0]
[[   0    1    0    0    0    0]
 [   1    1    0    0    0    0]
 [   2    1    0    0    0    0]
 [   3    1    0    0    0    0]
 [1512 1511    0    0    1    0]]
direction: [0, 1]
first left_right: [0, -1]
first up_down: [1, 0]
check: [4, -1]
check: [5, 0]
check: [4, 1]
[[   0    1    0    0    0    0]
 [   1    1    0    0    0    0]
 [   2    1    0    0    0    0]
 [   3    1    0    0    0    0]
 [1512 1513    0    0    1    0]]
direction: [0, 1]
first left_right: [0, -1]
first up_down: [1, 0]
check: [4, 0]
[[   0    1    0    0    0    0]
 [   1    1    0    0    0    0]
 [   2    1    0    0    0    0]
 [   3    1    0    0    0    0]
 [1514 1513    0    0    1    0]]
di

 [1818 1819    0    0    1    0]]
direction: [0, 1]
first left_right: [0, -1]
first up_down: [1, 0]
check: [4, 0]
[[   0    1    0    0    0    0]
 [   1    1    0    0    0    0]
 [   2    1    0    0    0    0]
 [   3    1    0    0    0    0]
 [1820 1819    0    0    1    0]]
direction: [0, 1]
first left_right: [0, -1]
first up_down: [1, 0]
check: [4, -1]
check: [5, 0]
check: [4, 1]
[[   0    1    0    0    0    0]
 [   1    1    0    0    0    0]
 [   2    1    0    0    0    0]
 [   3    1    0    0    0    0]
 [1820 1821    0    0    1    0]]
direction: [0, 1]
first left_right: [0, -1]
first up_down: [1, 0]
check: [4, 0]
[[   0    1    0    0    0    0]
 [   1    1    0    0    0    0]
 [   2    1    0    0    0    0]
 [   3    1    0    0    0    0]
 [1822 1821    0    0    1    0]]
direction: [0, 1]
first left_right: [0, -1]
first up_down: [1, 0]
check: [4, -1]
check: [5, 0]
check: [4, 1]
[[   0    1    0    0    0    0]
 [   1    1    0    0    0    0]
 [   2    1    0    0   

first up_down: [1, 0]
check: [4, 0]
[[   0    1    0    0    0    0]
 [   1    1    0    0    0    0]
 [   2    1    0    0    0    0]
 [   3    1    0    0    0    0]
 [2094 2093    0    0    1    0]]
direction: [0, 1]
first left_right: [0, -1]
first up_down: [1, 0]
check: [4, -1]
check: [5, 0]
check: [4, 1]
[[   0    1    0    0    0    0]
 [   1    1    0    0    0    0]
 [   2    1    0    0    0    0]
 [   3    1    0    0    0    0]
 [2094 2095    0    0    1    0]]
direction: [0, 1]
first left_right: [0, -1]
first up_down: [1, 0]
check: [4, 0]
[[   0    1    0    0    0    0]
 [   1    1    0    0    0    0]
 [   2    1    0    0    0    0]
 [   3    1    0    0    0    0]
 [2096 2095    0    0    1    0]]
direction: [0, 1]
first left_right: [0, -1]
first up_down: [1, 0]
check: [4, -1]
check: [5, 0]
check: [4, 1]
[[   0    1    0    0    0    0]
 [   1    1    0    0    0    0]
 [   2    1    0    0    0    0]
 [   3    1    0    0    0    0]
 [2096 2097    0    0    1    0]]
di

check: [4, 1]
[[   0    1    0    0    0    0]
 [   1    1    0    0    0    0]
 [   2    1    0    0    0    0]
 [   3    1    0    0    0    0]
 [2426 2427    0    0    1    0]]
direction: [0, 1]
first left_right: [0, -1]
first up_down: [1, 0]
check: [4, 0]
[[   0    1    0    0    0    0]
 [   1    1    0    0    0    0]
 [   2    1    0    0    0    0]
 [   3    1    0    0    0    0]
 [2428 2427    0    0    1    0]]
direction: [0, 1]
first left_right: [0, -1]
first up_down: [1, 0]
check: [4, -1]
check: [5, 0]
check: [4, 1]
[[   0    1    0    0    0    0]
 [   1    1    0    0    0    0]
 [   2    1    0    0    0    0]
 [   3    1    0    0    0    0]
 [2428 2429    0    0    1    0]]
direction: [0, 1]
first left_right: [0, -1]
first up_down: [1, 0]
check: [4, 0]
[[   0    1    0    0    0    0]
 [   1    1    0    0    0    0]
 [   2    1    0    0    0    0]
 [   3    1    0    0    0    0]
 [2430 2429    0    0    1    0]]
direction: [0, 1]
first left_right: [0, -1]
first up_

 [2730 2729    0    0    1    0]]
direction: [0, 1]
first left_right: [0, -1]
first up_down: [1, 0]
check: [4, -1]
check: [5, 0]
check: [4, 1]
[[   0    1    0    0    0    0]
 [   1    1    0    0    0    0]
 [   2    1    0    0    0    0]
 [   3    1    0    0    0    0]
 [2730 2731    0    0    1    0]]
direction: [0, 1]
first left_right: [0, -1]
first up_down: [1, 0]
check: [4, 0]
[[   0    1    0    0    0    0]
 [   1    1    0    0    0    0]
 [   2    1    0    0    0    0]
 [   3    1    0    0    0    0]
 [2732 2731    0    0    1    0]]
direction: [0, 1]
first left_right: [0, -1]
first up_down: [1, 0]
check: [4, -1]
check: [5, 0]
check: [4, 1]
[[   0    1    0    0    0    0]
 [   1    1    0    0    0    0]
 [   2    1    0    0    0    0]
 [   3    1    0    0    0    0]
 [2732 2733    0    0    1    0]]
direction: [0, 1]
first left_right: [0, -1]
first up_down: [1, 0]
check: [4, 0]
[[   0    1    0    0    0    0]
 [   1    1    0    0    0    0]
 [   2    1    0    0   

direction: [0, 1]
first left_right: [0, -1]
first up_down: [1, 0]
check: [4, -1]
check: [5, 0]
check: [4, 1]
[[   0    1    0    0    0    0]
 [   1    1    0    0    0    0]
 [   2    1    0    0    0    0]
 [   3    1    0    0    0    0]
 [3010 3011    0    0    1    0]]
direction: [0, 1]
first left_right: [0, -1]
first up_down: [1, 0]
check: [4, 0]
[[   0    1    0    0    0    0]
 [   1    1    0    0    0    0]
 [   2    1    0    0    0    0]
 [   3    1    0    0    0    0]
 [3012 3011    0    0    1    0]]
direction: [0, 1]
first left_right: [0, -1]
first up_down: [1, 0]
check: [4, -1]
check: [5, 0]
check: [4, 1]
[[   0    1    0    0    0    0]
 [   1    1    0    0    0    0]
 [   2    1    0    0    0    0]
 [   3    1    0    0    0    0]
 [3012 3013    0    0    1    0]]
direction: [0, 1]
first left_right: [0, -1]
first up_down: [1, 0]
check: [4, 0]
[[   0    1    0    0    0    0]
 [   1    1    0    0    0    0]
 [   2    1    0    0    0    0]
 [   3    1    0    0    

direction: [0, 1]
first left_right: [0, -1]
first up_down: [1, 0]
check: [4, 0]
[[   0    1    0    0    0    0]
 [   1    1    0    0    0    0]
 [   2    1    0    0    0    0]
 [   3    1    0    0    0    0]
 [3344 3343    0    0    1    0]]
direction: [0, 1]
first left_right: [0, -1]
first up_down: [1, 0]
check: [4, -1]
check: [5, 0]
check: [4, 1]
[[   0    1    0    0    0    0]
 [   1    1    0    0    0    0]
 [   2    1    0    0    0    0]
 [   3    1    0    0    0    0]
 [3344 3345    0    0    1    0]]
direction: [0, 1]
first left_right: [0, -1]
first up_down: [1, 0]
check: [4, 0]
[[   0    1    0    0    0    0]
 [   1    1    0    0    0    0]
 [   2    1    0    0    0    0]
 [   3    1    0    0    0    0]
 [3346 3345    0    0    1    0]]
direction: [0, 1]
first left_right: [0, -1]
first up_down: [1, 0]
check: [4, -1]
check: [5, 0]
check: [4, 1]
[[   0    1    0    0    0    0]
 [   1    1    0    0    0    0]
 [   2    1    0    0    0    0]
 [   3    1    0    0    

direction: [0, 1]
first left_right: [0, -1]
first up_down: [1, 0]
check: [4, 0]
[[   0    1    0    0    0    0]
 [   1    1    0    0    0    0]
 [   2    1    0    0    0    0]
 [   3    1    0    0    0    0]
 [3594 3593    0    0    1    0]]
direction: [0, 1]
first left_right: [0, -1]
first up_down: [1, 0]
check: [4, -1]
check: [5, 0]
check: [4, 1]
[[   0    1    0    0    0    0]
 [   1    1    0    0    0    0]
 [   2    1    0    0    0    0]
 [   3    1    0    0    0    0]
 [3594 3595    0    0    1    0]]
direction: [0, 1]
first left_right: [0, -1]
first up_down: [1, 0]
check: [4, 0]
[[   0    1    0    0    0    0]
 [   1    1    0    0    0    0]
 [   2    1    0    0    0    0]
 [   3    1    0    0    0    0]
 [3596 3595    0    0    1    0]]
direction: [0, 1]
first left_right: [0, -1]
first up_down: [1, 0]
check: [4, -1]
check: [5, 0]
check: [4, 1]
[[   0    1    0    0    0    0]
 [   1    1    0    0    0    0]
 [   2    1    0    0    0    0]
 [   3    1    0    0    

first up_down: [1, 0]
check: [4, -1]
check: [5, 0]
check: [4, 1]
[[   0    1    0    0    0    0]
 [   1    1    0    0    0    0]
 [   2    1    0    0    0    0]
 [   3    1    0    0    0    0]
 [3926 3927    0    0    1    0]]
direction: [0, 1]
first left_right: [0, -1]
first up_down: [1, 0]
check: [4, 0]
[[   0    1    0    0    0    0]
 [   1    1    0    0    0    0]
 [   2    1    0    0    0    0]
 [   3    1    0    0    0    0]
 [3928 3927    0    0    1    0]]
direction: [0, 1]
first left_right: [0, -1]
first up_down: [1, 0]
check: [4, -1]
check: [5, 0]
check: [4, 1]
[[   0    1    0    0    0    0]
 [   1    1    0    0    0    0]
 [   2    1    0    0    0    0]
 [   3    1    0    0    0    0]
 [3928 3929    0    0    1    0]]
direction: [0, 1]
first left_right: [0, -1]
first up_down: [1, 0]
check: [4, 0]
[[   0    1    0    0    0    0]
 [   1    1    0    0    0    0]
 [   2    1    0    0    0    0]
 [   3    1    0    0    0    0]
 [3930 3929    0    0    1    0]]
di

check: [4, 0]
[[   0    1    0    0    0    0]
 [   1    1    0    0    0    0]
 [   2    1    0    0    0    0]
 [   3    1    0    0    0    0]
 [4260 4259    0    0    1    0]]
direction: [0, 1]
first left_right: [0, -1]
first up_down: [1, 0]
check: [4, -1]
check: [5, 0]
check: [4, 1]
[[   0    1    0    0    0    0]
 [   1    1    0    0    0    0]
 [   2    1    0    0    0    0]
 [   3    1    0    0    0    0]
 [4260 4261    0    0    1    0]]
direction: [0, 1]
first left_right: [0, -1]
first up_down: [1, 0]
check: [4, 0]
[[   0    1    0    0    0    0]
 [   1    1    0    0    0    0]
 [   2    1    0    0    0    0]
 [   3    1    0    0    0    0]
 [4262 4261    0    0    1    0]]
direction: [0, 1]
first left_right: [0, -1]
first up_down: [1, 0]
check: [4, -1]
check: [5, 0]
check: [4, 1]
[[   0    1    0    0    0    0]
 [   1    1    0    0    0    0]
 [   2    1    0    0    0    0]
 [   3    1    0    0    0    0]
 [4262 4263    0    0    1    0]]
direction: [0, 1]
first 

KeyboardInterrupt: 

In [5]:
check = [5,0]
(maze[check[0]][check[1]] != 1) & (check[0]>=0) & (check[0] < len(maze)) & (check[1] >= 0) & (check[1] < len(maze[0]))

IndexError: list index out of range

In [9]:
print(np.array(maze))

[[0 1 0 0 0 0]
 [1 1 0 0 0 0]
 [2 1 0 0 0 0]
 [3 1 0 0 0 0]
 [4 0 0 0 1 0]]


In [7]:
maze[0][5]

0