In [166]:
# %load a_star.py
# Finish A* search function that can find path from starting point to the end
# The robot starts from start position (0,0) and finds a path to end position (4, 5)
# In the maze, 0 is open path while 1 means wall (a robot cannot pass through wall)
# please write your heuristic matrix, and fill unvisited position with -1,
# cost of each movement is 1, as shown in the example below

# example result:
# [[0, -1, -1, -1, -1, -1],
#  [1, -1, -1, -1, -1, -1],
#  [2, -1, -1, -1, -1, -1],
#  [3, -1,  8, 10, 12, 14],
#  [4,  5,  6,  7, -1, 15]]

# the maze robot need to find a path
maze = [[0, 1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 1, 0]]

start = [0, 0] # starting position
end = [len(maze)-1, len(maze[0])-1] # ending position
cost = 1 # cost per movement

move = [[-1, 0 ], # go up
        [ 0, -1], # go left
        [ 1, 0 ], # go down
        [ 0, 1 ]] # go right


### 1. make your own heuristic
heuristic = [[0, 0, 0, 0, 0, 0],
             [0, 0, 0, 0, 0, 0],
             [0, 0, 0, 0, 0, 0],
             [0, 0, 0, 0, 0, 0],
             [0, 0, 0, 0, 0, 0]]


### 2. finish the A* search funciton below
# def search(maze, start, end, cost, heuristic):
    
#     # first convert everything to numpy array for each slicking/referece
#     import numpy as np
    
#     maze = np.array(maze)
#     start = np.array(start)
#     end = np.array(end)
#     move = np.array([[-1, 0 ], # go up
#         [ 0, -1], # go left
#         [ 1, 0 ], # go down
#         [ 0, 1 ]] # go right
#     )
#     # initialize starting location and total cost
#     ind = start
#     cumulative_cost = 0
    
#     while (ind[0]!= end[0] | ind[1]!= end[1]):
#         # get direction
#         direction = end - start
#         direction = np.array([1 if i > 0 else 0 for i in direction ])
#         # get next move from move matrix
        
#         # left_right
#         left_right = move[[1,3]][direction[0]]
#         # up_down
#         left_right = move[[0,2]][direction[1]]
        
#         # check if already travelled
#         for next_move in [left_right, up_down, -left_right, -up_down]: 
#             check = ind + next_move
#             if maze[check]!= 1: # not wall
#                 # make the move
#                 ind = check
#                 maze[ind] = cumulative_cost +1
#                 cumulative_cost = maze[ind]
#                 print(maze)

#     return 

# search(maze, start, end, cost, heuristic)

In [167]:
import numpy as np

maze = np.array(maze)
start = np.array(start)
end = np.array(end)
move = np.array([[-1, 0 ], # go up
    [ 0, -1], # go left
    [ 1, 0 ], # go down
    [ 0, 1 ]] # go right
)
# initialize starting location and total cost
ind = start
cumulative_cost = 0

print(maze)

while (ind[0]!= end[0] | ind[1]!= end[1]):
    # get direction
    direction = end - start
    direction = np.array([1 if i > 0 else 0 for i in direction ])
    # get potential next move from move matrix
    left_right = move[[1,3]][direction[0]] # left_right
    up_down = move[[0,2]][direction[1]] # up_down
    print(left_right)

    # check if already travelled or at the bundary
    breaker = 0
    for next_move in [left_right, up_down, -left_right, -up_down]:
        if breaker ==1:
            continue
        else:
            check = ind + next_move    
            print(check)
            if (maze[check[0], check[1]] != 1) & (check[0]>=0) & (check[0] < maze.shape[0]) & (check[1] >= 0) & (check[1] < maze.shape[1]): # no wall, make the move
                ind = check
                maze[ind[0],ind[1]] = cumulative_cost +1
                cumulative_cost = maze[ind[0],ind[1]]
                breaker =1
                print(maze)

[[0 1 0 0 0 0]
 [0 1 0 0 0 0]
 [0 1 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 0 0 1 0]]
[0 1]
[0 1]
[1 0]
[[0 1 0 0 0 0]
 [1 1 0 0 0 0]
 [0 1 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 0 0 1 0]]
[0 1]
[1 1]
[2 0]
[[0 1 0 0 0 0]
 [1 1 0 0 0 0]
 [2 1 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 0 0 1 0]]
[0 1]
[2 1]
[3 0]
[[0 1 0 0 0 0]
 [1 1 0 0 0 0]
 [2 1 0 0 0 0]
 [3 1 0 0 0 0]
 [0 0 0 0 1 0]]
[0 1]
[3 1]
[4 0]
[[0 1 0 0 0 0]
 [1 1 0 0 0 0]
 [2 1 0 0 0 0]
 [3 1 0 0 0 0]
 [4 0 0 0 1 0]]


In [152]:
maze.shape

(5, 6)